### ISSUE TITLE
Messes up Stylus auto completion

### ISSUE THREAD

**Issue by ghost** [RonanDrouglazet/TypescriptCompletion#3]
After installing this plugin, stylus completion stopped working. I deleted this and it works again. 
Why this plugin brokes files with extension styl?

**Comment by RonanDrouglazet** [comment]
Hi @atilkan, Thanks for the report ! 

It's strange... i'm currently doing things only when you'r current editing file is a .ts file as you can see here

https://github.com/RonanDrouglazet/TypescriptCompletion/blob/master/TSCompletion.py#L50
https://github.com/RonanDrouglazet/TypescriptCompletion/blob/master/TSCompletion.py#L257

I have a question for you before dig into it, did you still use this ts plugin (`TypescriptCompletion`) ? Because when the official plugin comes out (https://github.com/Microsoft/TypeScript-Sublime-Plugin) i've stopped the dev on mine...

If you still use it for any reason, i will dig into this issue !

**Comment by ghost** [comment]
No, i had to delete. It doesn't let me work. I just wanted to test and see what it does. Thanks.
But this plugin still there and confuse people. Maybe you should remove it from packagecontroller.
